--- 
after_script: 
  - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"
before_script: 
  - "composer update --no-dev"
  - "wget https://scrutinizer-ci.com/ocular.phar"
language: php
php: 
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - hhvm
script: 
  - "phpunit --bootstrap test/config.php --coverage-clover coverage.clover test"
sudo: required
